### ISSUE TITLE
Ability to programatically stream osx-audio?

### ISSUE THREAD

**Issue by jamesmorgan** [fardog/node-webcast-osx-audio#3]
I would like to programatically use the library but not sure how to?

I have tried to spawn the process using `exec` but cant seem to get hold of the `url' address that gets pumped out e.g.

````js
    webCastProcess = exec('./node_modules/.bin/webcast-audio', function (error, stdout, stderr) {
        if (stdout) {
            console.log("LAUNCHED", stdout);
        }
        if (stderr) {
            console.log("ERROR", stderr);
        }
        if (error) {
            console.log("error", error);
        }
    });
````

I see it `streaming at http://192.168.1.8:3000/stream.mp3` in the console but not from my log statements e.g. `console.log("LAUNCHED", stdout);` 

Any ideas about this or know how I could easily use it programatically?

Thanks for the library as well, seems to work well!

**Comment by jamesmorgan** [comment]
EDIT: I was incorrectly using `exec`, beginners mistake. Usage now like this:

````
 var webCastProcess = exec('./node_modules/.bin/webcast-audio', {async: true});
    webCastProcess.stdout.on('data', function (data) {
        console.log("LAUNCHED", data);
    });
    webCastProcess.stderr.on('data', function (data) {
        console.log("ERROR", data);
    });
    webCastProcess.on('exit', function (code) {
        console.log('child process exited with code ' + code);
    });
````

It would still be nice to do this programatically using something other than `exec`.

**Comment by fardog** [comment]
You can do this, it's done in my `chromecast-osx-audio` module: https://github.com/fardog/node-chromecast-osx-audio/blob/master/lib/index.js

The API isn't documented, and admittedly not that great; you can use properties on the `Webcast` instance that you create to get information about it (the express app itself is at `instance.app`).

You can also use the [osx-audio](https://github.com/fardog/node-osx-audio) module that this wraps directly, if you need more control over what's happening. This is just a pretty simple express server that exposes the streams created by that module.

There are lots of things I'd like to improve about this module, but unfortunately it's unmaintained for now—I no longer have a Mac on which to test this stuff, so I can't make any real changes; am hoping at some point another maintainer can pick up these few plugins and make them better.

Anyhow, I've created #4 with a help-wanted tag for improving the documentation around this.

Best of luck!

**Comment by jamesmorgan** [comment]
Thanks for the reply - I have a working version of my app to this library so thanks - https://github.com/jamesmorgan/devicecast - I will take a look at the link and move to using it correctly now I see how, thanks again!

**Comment by jamesmorgan** [comment]
Hi, I am having issue trying to use this programatically, can chance you have seen this or have on how to fix this?

I'm using in with electron - as seen here: https://github.com/jamesmorgan/devicecast/blob/master/device/LocalSoundStreamerWebcast.js#L2

I always get the following error when starting the app with `required('webcast-osx-audio')` in.

````js
Uncaught Exception:
Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:140:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:140:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/Users/jamesmorgan/Dropbox/workspace-js/devicecast/node_modules/webcast-osx-audio/node_modules/lame/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/jamesmorgan/Dropbox/workspace-js/devicecast/node_modules/webcast-osx-audio/node_modules/lame/lib/bindings.js:1:116)
````

Have you ever used this with electron?

**Comment by fardog** [comment]
@jamesmorgan i haven't used it with electron, but that message is from trying to use it on something that's not node 0.10.x; i'm assuming electron is packaging something newer. you might want to take a look at this project https://github.com/andresgottlieb/soundcast which packages the chromecast version of webcast-osx-audio *and* node 0.10.x presumably to work around this.
