### ISSUE TITLE
Directing audio with Soundflower

### ISSUE THREAD

**Issue by c10b10** [fardog/node-webcast-osx-audio#6]
I have directed the audio from Ableton to Soundflower. How do I make `webcast-osx-audio` use that as input?

**Comment by fardog** [comment]
`osx-audio`—the underlying module that's used to get audio input—directs audio from whatever is set as the system input (that is, as selected from the system preferences sound pane). you should be able to select the input there, and restart `webcast-osx-audio` to have it grab that output.
